version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: angular-client # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - ./angular-client:/app
      - /app/node_modules

  express: #name of the second service
    build: express-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - mongodb
      - redis

  mongodb: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
    volumes:
        - ./.docker/mongodb:/data/db
    restart: always

  redis:
      image: "redis:alpine"
      hostname: redis
      ports:
        - "6379:6379"
      command: redis-server --appendonly yes
      volumes:
        - ./.docker/redis:/data